import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const publicRoot = resolve(import.meta.dirname, "..", "public");

const t = (ar, en) => `<span x-show="locale === 'ar'">${ar}</span><span x-show="locale === 'en'">${en}</span>`;

function shippingSubnav(active) {
  const link = (href, key, ar, en) => `<a href="${href}" class="inline-flex h-control-sm shrink-0 items-center rounded-md px-3 text-xs font-semibold ${active === key ? "bg-ink text-white" : "text-muted hover:bg-card hover:text-ink"}"${active === key ? ' aria-current="page"' : ""}>${t(ar, en)}</a>`;
  return `<!-- component: shipping-section-navigation -->
      <nav class="border-b border-border bg-subtle/70 px-page-mobile py-2 sm:px-page-tablet" :aria-label="locale === 'ar' ? 'أقسام الشحن' : 'Shipping sections'">
        <div class="mx-auto flex max-w-app gap-1 overflow-x-auto">
          ${link("/shipping-zones.html", "zones", "مناطق الشحن", "Shipping zones")}
          ${link("/custom-locations.html", "locations", "المواقع المخصصة", "Custom locations")}
          ${link("/shipping-integrations.html", "integrations", "التكاملات", "Integrations")}
        </div>
      </nav>
      <!-- /component: shipping-section-navigation -->`;
}

function shell({ title, description, active, state, content }) {
  return `<!doctype html>
<html lang="ar" dir="rtl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="${description}" />
    <title>lala — ${title}</title>
    <link rel="stylesheet" href="/fonts.css" />
    <link rel="stylesheet" href="/batch1.css" />
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <script defer src="/alpine-fallback.js"></script>
  </head>
  <body x-data="{ locale: 'ar', ${state} }" :dir="locale === 'ar' ? 'rtl' : 'ltr'" class="min-h-screen bg-canvas font-sans text-ink">
    <!-- component: shipping-app-shell -->
    <aside class="fixed inset-y-0 start-0 z-sidebar hidden w-sidebar flex-col border-e border-border bg-card lg:flex"><nav></nav></aside>
    <div class="min-h-screen lg:ps-sidebar">
      <header class="sticky top-0 z-header flex h-app-header items-center gap-3 border-b border-border bg-card/95 px-4 backdrop-blur sm:px-6">
        <a href="/app-shell.html" class="font-semibold lg:hidden">lala</a>
        <p class="min-w-0 flex-1 truncate text-xs text-muted">${t("متجر لونا / الشحن", "Luna Store / Shipping")}</p>
        <button class="hidden h-9 items-center gap-2 rounded-lg border border-border bg-card px-3 shadow-xs sm:flex"><span class="size-2 rounded-full bg-success"></span><span class="text-xs text-muted">${t("المحفظة", "Wallet")}</span><span dir="ltr" class="font-mono text-xs font-semibold">EGP 1,240.00</span></button>
        <button @click="locale = locale === 'ar' ? 'en' : 'ar'; document.documentElement.lang = locale; document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr'" class="h-9 rounded-lg border border-border px-3 text-xs font-semibold"><span x-show="locale === 'ar'">EN</span><span x-show="locale === 'en'">عربي</span></button>
        <span class="grid size-9 place-items-center rounded-full bg-ink text-xs font-semibold text-white">AM</span>
      </header>
      ${shippingSubnav(active)}
      ${content}
    </div>
    <!-- /component: shipping-app-shell -->
  </body>
</html>`;
}

const zones = shell({
  title: "Shipping zones",
  description: "lala shipping zones list with coverage, prices, enabled states, empty state, and overlap protection",
  active: "zones",
  state: "view: 'data'",
  content: `<!-- component: shipping-zones-list -->
      <main class="p-page-mobile sm:p-page-tablet lg:p-page-desktop"><div class="mx-auto max-w-app">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-semibold uppercase tracking-section text-accent">Batch 7 · Shipping</p><h1 class="mt-1 text-2xl font-bold">${t("مناطق الشحن", "Shipping zones")}</h1><p class="mt-1 text-sm text-muted">${t("حدد التغطية والسعر مرة واحدة، والطلبات الجديدة تستخدم السعر الحالي فقط.", "Define coverage and price once; only new orders use the current price.")}</p></div><a href="/shipping-zone-editor.html" class="inline-flex h-control-md items-center justify-center rounded-md bg-accent px-4 text-sm font-semibold text-white">${t("إضافة منطقة", "Add zone")}</a></div>
        <section class="mt-5 grid gap-3 sm:grid-cols-3"><div class="rounded-xl border border-border bg-card p-4 shadow-xs"><p class="text-xs text-muted">${t("مناطق مفعلة", "Enabled zones")}</p><p class="mt-2 font-mono text-2xl font-semibold">4</p></div><div class="rounded-xl border border-border bg-card p-4 shadow-xs"><p class="text-xs text-muted">${t("محافظات مغطاة", "Covered governorates")}</p><p class="mt-2 font-mono text-2xl font-semibold">9</p></div><div class="rounded-xl border border-success/20 bg-success-soft p-4"><p class="text-xs text-success">${t("شحن مجاني", "Free shipping")}</p><p class="mt-2 font-mono text-2xl font-semibold text-success">1</p></div></section>
        <section class="mt-5 overflow-hidden rounded-xl border border-border bg-card shadow-xs">
          <div class="flex flex-col gap-3 border-b border-border p-4 sm:flex-row sm:items-center"><label class="min-w-0 flex-1"><span class="sr-only">Search zones</span><input class="h-input w-full rounded-md border border-border-strong px-3 text-sm outline-none focus:border-accent" :placeholder="locale === 'ar' ? 'ابحث باسم المنطقة أو المحافظة' : 'Search zone or governorate'" /></label><button @click="view='data'" class="h-input rounded-md border border-border-strong px-3 text-sm font-semibold">${t("مسح الفلاتر", "Clear")}</button><div class="flex gap-1 rounded-md bg-subtle p-1"><button @click="view='data'" :class="view==='data' ? 'bg-ink text-white' : 'text-muted'" class="rounded px-2 py-1 text-xs">Data</button><button @click="view='empty'" :class="view==='empty' ? 'bg-ink text-white' : 'text-muted'" class="rounded px-2 py-1 text-xs">Empty</button></div></div>
          <!-- component: shipping-zones-table -->
          <div x-show="view==='data'" class="overflow-x-auto"><table class="w-full min-w-table-wide text-sm leading-5"><thead class="bg-subtle text-xs font-semibold text-muted"><tr class="h-table-row border-b border-border"><th class="px-table-cell-x py-table-cell-y text-start">${t("المنطقة", "Zone")}</th><th class="px-table-cell-x py-table-cell-y text-start">${t("التغطية", "Coverage")}</th><th class="px-table-cell-x py-table-cell-y text-end">${t("السعر", "Price")}</th><th class="px-table-cell-x py-table-cell-y text-start">${t("الحالة", "State")}</th><th class="px-table-cell-x py-table-cell-y text-end">${t("الإجراء", "Action")}</th></tr></thead><tbody class="divide-y divide-border">
            <tr class="h-table-row hover:bg-subtle"><td class="px-table-cell-x py-table-cell-y"><a href="/shipping-zone-editor.html" class="font-semibold text-accent">${t("القاهرة الكبرى", "Greater Cairo")}</a></td><td class="px-table-cell-x py-table-cell-y"><p>${t("القاهرة والجيزة", "Cairo and Giza")}</p><p class="text-xs text-muted">${t("18 مدينة ومنطقة", "18 cities and areas")}</p></td><td dir="ltr" class="px-table-cell-x py-table-cell-y text-end font-mono text-xs font-semibold">EGP 80.00</td><td class="px-table-cell-x py-table-cell-y"><span class="rounded-full bg-success-soft px-2.5 py-1 text-xs font-semibold text-success">${t("مفعلة", "Enabled")}</span></td><td class="px-table-cell-x py-table-cell-y text-end"><a href="/shipping-zone-editor.html" class="text-xs font-semibold text-accent">${t("تعديل", "Edit")}</a></td></tr>
            <tr class="h-table-row hover:bg-subtle"><td class="px-table-cell-x py-table-cell-y"><a href="/shipping-zone-editor.html" class="font-semibold text-accent">${t("الإسكندرية", "Alexandria")}</a></td><td class="px-table-cell-x py-table-cell-y"><p>${t("محافظة الإسكندرية", "Alexandria governorate")}</p><p class="text-xs text-muted">${t("كل المدن والمناطق", "All cities and areas")}</p></td><td dir="ltr" class="px-table-cell-x py-table-cell-y text-end font-mono text-xs font-semibold">EGP 95.00</td><td class="px-table-cell-x py-table-cell-y"><span class="rounded-full bg-success-soft px-2.5 py-1 text-xs font-semibold text-success">${t("مفعلة", "Enabled")}</span></td><td class="px-table-cell-x py-table-cell-y text-end"><a href="/shipping-zone-editor.html" class="text-xs font-semibold text-accent">${t("تعديل", "Edit")}</a></td></tr>
            <tr class="h-table-row hover:bg-subtle"><td class="px-table-cell-x py-table-cell-y"><a href="/shipping-zone-editor.html" class="font-semibold text-accent">${t("عروض الدقهلية", "Dakahlia offer")}</a></td><td class="px-table-cell-x py-table-cell-y"><p>${t("المنصورة وطلخا", "Mansoura and Talkha")}</p><p class="text-xs text-muted">${t("مدينتان", "2 cities")}</p></td><td class="px-table-cell-x py-table-cell-y text-end"><span class="rounded-full bg-success-soft px-2.5 py-1 text-xs font-semibold text-success">${t("شحن مجاني", "Free shipping")}</span></td><td class="px-table-cell-x py-table-cell-y"><span class="rounded-full bg-success-soft px-2.5 py-1 text-xs font-semibold text-success">${t("مفعلة", "Enabled")}</span></td><td class="px-table-cell-x py-table-cell-y text-end"><a href="/shipping-zone-editor.html" class="text-xs font-semibold text-accent">${t("تعديل", "Edit")}</a></td></tr>
            <tr class="h-table-row hover:bg-subtle"><td class="px-table-cell-x py-table-cell-y"><a href="/shipping-zone-editor.html" class="font-semibold text-accent">${t("الصعيد", "Upper Egypt")}</a></td><td class="px-table-cell-x py-table-cell-y"><p>${t("أسيوط وسوهاج", "Assiut and Sohag")}</p><p class="text-xs text-muted">${t("كل المدن", "All cities")}</p></td><td dir="ltr" class="px-table-cell-x py-table-cell-y text-end font-mono text-xs font-semibold">EGP 135.00</td><td class="px-table-cell-x py-table-cell-y"><span class="rounded-full bg-subtle px-2.5 py-1 text-xs font-semibold text-muted">${t("متوقفة", "Disabled")}</span></td><td class="px-table-cell-x py-table-cell-y text-end"><a href="/shipping-zone-editor.html" class="text-xs font-semibold text-accent">${t("تعديل", "Edit")}</a></td></tr>
          </tbody></table></div>
          <!-- /component: shipping-zones-table -->
          <div x-show="view==='empty'" x-cloak class="px-6 py-16 text-center"><span class="mx-auto grid size-12 place-items-center rounded-xl bg-accent-soft text-accent">⌁</span><h2 class="mt-4 font-bold">${t("لسه مفيش مناطق شحن", "No shipping zones yet")}</h2><p class="mt-1 text-sm text-muted">${t("أضف أول منطقة عشان يقدر العميل يكمل الطلب.", "Add the first zone so customers can complete checkout.")}</p><a href="/shipping-zone-editor.html" class="mt-4 inline-flex h-control-md items-center rounded-md bg-accent px-4 text-sm font-semibold text-white">${t("إضافة منطقة", "Add zone")}</a></div>
        </section>
        <p class="mt-4 rounded-lg border border-info/25 bg-info-soft p-4 text-xs leading-arabic text-info">${t("أي تعديل في السعر يطبق على الطلبات الجديدة فقط. الطلبات القديمة تحتفظ بسعر الشحن وقت إنشائها.", "Price changes apply only to new orders. Existing orders keep their original shipping price.")}</p>
      </div></main>
      <!-- /component: shipping-zones-list -->`,
});

const zoneEditor = shell({
  title: "Shipping zone editor",
  description: "lala shipping zone editor for Egypt governorates, cities, areas, free shipping, and overlap validation",
  active: "zones",
  state: "freeShipping: false, preview: 'valid'",
  content: `<!-- component: shipping-zone-editor -->
      <main class="p-page-mobile sm:p-page-tablet lg:p-page-desktop"><div class="mx-auto max-w-app">
        <div class="flex flex-col gap-4 border-b border-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><a href="/shipping-zones.html" class="text-xs font-semibold text-accent">${t("← مناطق الشحن", "← Shipping zones")}</a><h1 class="mt-2 text-2xl font-bold">${t("تعديل منطقة القاهرة الكبرى", "Edit Greater Cairo zone")}</h1><p class="mt-1 text-sm text-muted">${t("حدد تغطية غير متداخلة وسعرًا واحدًا لهذه المنطقة.", "Define non-overlapping coverage and one price for this zone.")}</p></div><div class="flex gap-2"><button class="h-control-md rounded-md border border-border-strong px-4 text-sm font-semibold">${t("إلغاء", "Cancel")}</button><button class="h-control-md rounded-md bg-accent px-4 text-sm font-semibold text-white">${t("حفظ المنطقة", "Save zone")}</button></div></div>
        <div class="mt-6 grid gap-6 xl:grid-cols-editor">
          <div class="space-y-6">
            <section class="rounded-xl border border-border bg-card p-5 shadow-xs"><h2 class="font-bold">${t("بيانات المنطقة", "Zone details")}</h2><div class="mt-4 grid gap-5 sm:grid-cols-2"><label class="block sm:col-span-2"><span class="mb-1.5 block text-sm font-semibold">${t("اسم المنطقة", "Zone name")}</span><input value="القاهرة الكبرى" class="h-input w-full rounded-md border border-border-strong px-3 text-sm outline-none focus:border-accent" /></label><label class="flex items-center justify-between rounded-lg border border-border p-4 sm:col-span-2"><span><span class="block text-sm font-semibold">${t("المنطقة مفعلة", "Zone enabled")}</span><span class="mt-1 block text-xs text-muted">${t("تظهر في Checkout فور الحفظ.", "Available at checkout after saving.")}</span></span><input checked type="checkbox" class="size-5 accent-accent" /></label></div></section>
            <!-- component: coverage-picker -->
            <section class="rounded-xl border border-border bg-card p-5 shadow-xs"><div class="flex items-start justify-between gap-4"><div><h2 class="font-bold">${t("التغطية", "Coverage")}</h2><p class="mt-1 text-xs text-muted">${t("مصر محددة تلقائيًا: محافظة ← مدينة ← منطقة.", "Egypt is fixed: governorate → city → area.")}</p></div><span class="rounded-full bg-accent-soft px-2.5 py-1 font-mono text-xs font-semibold text-accent">18</span></div><div class="mt-5 grid gap-4 lg:grid-cols-3"><section class="rounded-lg border border-accent bg-accent-soft p-4"><p class="text-xs font-semibold text-accent">${t("المحافظات", "Governorates")}</p><label class="mt-3 flex items-center gap-2 text-sm font-semibold"><input checked type="checkbox" class="size-4 accent-accent" />${t("القاهرة", "Cairo")}</label><label class="mt-3 flex items-center gap-2 text-sm"><input checked type="checkbox" class="size-4 accent-accent" />${t("الجيزة", "Giza")}</label><label class="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" class="size-4 accent-accent" />${t("القليوبية", "Qalyubia")}</label></section><section class="rounded-lg border border-border p-4"><p class="text-xs font-semibold text-muted">${t("مدن القاهرة", "Cairo cities")}</p><label class="mt-3 flex items-center gap-2 text-sm"><input checked type="checkbox" class="size-4 accent-accent" />${t("مدينة نصر", "Nasr City")}</label><label class="mt-3 flex items-center gap-2 text-sm"><input checked type="checkbox" class="size-4 accent-accent" />${t("القاهرة الجديدة", "New Cairo")}</label><label class="mt-3 flex items-center gap-2 text-sm"><input checked type="checkbox" class="size-4 accent-accent" />${t("المعادي", "Maadi")}</label></section><section class="rounded-lg border border-border p-4"><p class="text-xs font-semibold text-muted">${t("مناطق مدينة نصر", "Nasr City areas")}</p><label class="mt-3 flex items-center gap-2 text-sm"><input checked type="checkbox" class="size-4 accent-accent" />${t("الحي السابع", "7th District")}</label><label class="mt-3 flex items-center gap-2 text-sm"><input checked type="checkbox" class="size-4 accent-accent" />${t("الحي العاشر", "10th District")}</label><a href="/custom-locations.html" class="mt-4 block text-xs font-semibold text-accent">${t("إدارة المواقع المخصصة", "Manage custom locations")}</a></section></div></section>
            <!-- /component: coverage-picker -->
            <section class="rounded-xl border border-border bg-card p-5 shadow-xs"><h2 class="font-bold">${t("سعر الشحن", "Shipping price")}</h2><label class="mt-4 flex items-start gap-3"><input x-model="freeShipping" type="checkbox" class="mt-1 size-4 accent-accent" /><span><span class="block text-sm font-semibold">${t("شحن مجاني", "Free shipping")}</span><span class="block text-xs text-muted">${t("القيمة صفر تظهر للعميل كشحن مجاني.", "A zero price is shown to customers as Free shipping.")}</span></span></label><label x-show="!freeShipping" class="mt-4 block max-w-md"><span class="mb-1.5 block text-sm font-semibold">${t("السعر", "Price")}</span><div class="flex h-input overflow-hidden rounded-md border border-border-strong"><span class="grid place-items-center border-e border-border bg-subtle px-3 font-mono text-xs">EGP</span><input dir="ltr" value="80.00" class="min-w-0 flex-1 px-3 text-start font-mono text-xs outline-none" /></div></label><div x-show="freeShipping" x-cloak class="mt-4 rounded-lg bg-success-soft p-4 text-sm font-semibold text-success">${t("سيظهر للعميل: شحن مجاني", "Customer sees: Free shipping")}</div></section>
          </div>
          <aside class="self-start space-y-4 xl:sticky xl:top-24"><section class="rounded-xl border border-border bg-card p-5 shadow-xs"><h2 class="font-bold">${t("فحص الحالات", "State review")}</h2><div class="mt-4 grid gap-2"><button @click="preview='valid'" :class="preview==='valid' ? 'bg-ink text-white' : 'bg-subtle text-muted'" class="h-control-sm rounded-md px-3 text-xs">Valid</button><button @click="preview='overlap'" :class="preview==='overlap' ? 'bg-ink text-white' : 'bg-subtle text-muted'" class="h-control-sm rounded-md px-3 text-xs">Overlap blocked</button><button @click="preview='unsupported'" :class="preview==='unsupported' ? 'bg-ink text-white' : 'bg-subtle text-muted'" class="h-control-sm rounded-md px-3 text-xs">Unsupported</button></div></section><section x-show="preview==='valid'" class="rounded-xl border border-success/25 bg-success-soft p-4 text-sm text-success"><strong>${t("التغطية صالحة", "Coverage is valid")}</strong><p class="mt-1 text-xs leading-arabic">${t("لا يوجد تداخل مع أي منطقة مفعلة.", "No overlap with another active zone.")}</p></section><section x-show="preview==='overlap'" x-cloak class="rounded-xl border border-danger/25 bg-danger-soft p-4 text-sm text-danger"><strong>${t("لا يمكن الحفظ", "Cannot save")}</strong><p class="mt-1 text-xs leading-arabic">${t("مدينة نصر موجودة بالفعل داخل منطقة القاهرة الخاصة. أزل التداخل أو أوقف المنطقة الأخرى.", "Nasr City already belongs to the active Cairo Special zone. Remove the overlap or disable the other zone.")}</p></section><section x-show="preview==='unsupported'" x-cloak class="rounded-xl border border-warning/25 bg-warning-soft p-4 text-sm text-warning"><strong>${t("الموقع غير مدعوم", "Unsupported location")}</strong><p class="mt-1 text-xs leading-arabic">${t("المنطقة لن تظهر في Checkout قبل إضافتها للمواقع المدعومة.", "The area will not appear at checkout until it is added to supported locations.")}</p></section></aside>
        </div>
      </div></main>
      <!-- /component: shipping-zone-editor -->`,
});

const locations = shell({
  title: "Custom locations",
  description: "lala store-specific custom city and area management",
  active: "locations",
  state: "view: 'data', locationModal: false",
  content: `<!-- component: custom-locations -->
      <main class="p-page-mobile sm:p-page-tablet lg:p-page-desktop"><div class="mx-auto max-w-app">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-semibold uppercase tracking-section text-accent">Batch 7 · Shipping</p><h1 class="mt-1 text-2xl font-bold">${t("المواقع المخصصة", "Custom locations")}</h1><p class="mt-1 text-sm text-muted">${t("أضف مدينة أو منطقة خاصة بمتجرك فقط؛ لن تظهر لباقي المتاجر.", "Add a city or area private to this store; other stores will not see it.")}</p></div><button @click="locationModal=true" class="h-control-md rounded-md bg-accent px-4 text-sm font-semibold text-white">${t("إضافة موقع", "Add location")}</button></div>
        <section class="mt-5 overflow-hidden rounded-xl border border-border bg-card shadow-xs"><div class="flex flex-col gap-3 border-b border-border p-4 sm:flex-row sm:items-center"><label class="min-w-0 flex-1"><span class="sr-only">Search custom locations</span><input class="h-input w-full rounded-md border border-border-strong px-3 text-sm" :placeholder="locale === 'ar' ? 'ابحث بالمدينة أو المنطقة' : 'Search city or area'" /></label><div class="flex gap-1 rounded-md bg-subtle p-1"><button @click="view='data'" :class="view==='data' ? 'bg-ink text-white' : 'text-muted'" class="rounded px-2 py-1 text-xs">Data</button><button @click="view='empty'" :class="view==='empty' ? 'bg-ink text-white' : 'text-muted'" class="rounded px-2 py-1 text-xs">Empty</button></div></div>
          <div x-show="view==='data'" class="overflow-x-auto"><table class="w-full min-w-table-standard text-sm leading-5"><thead class="bg-subtle text-xs font-semibold text-muted"><tr class="h-table-row border-b border-border"><th class="px-table-cell-x py-table-cell-y text-start">${t("الاسم", "Name")}</th><th class="px-table-cell-x py-table-cell-y text-start">${t("النوع", "Type")}</th><th class="px-table-cell-x py-table-cell-y text-start">${t("يتبع", "Parent")}</th><th class="px-table-cell-x py-table-cell-y text-start">${t("الاستخدام", "Usage")}</th><th class="px-table-cell-x py-table-cell-y text-end">${t("الإجراء", "Action")}</th></tr></thead><tbody class="divide-y divide-border"><tr class="h-table-row hover:bg-subtle"><td class="px-table-cell-x py-table-cell-y font-semibold">${t("امتداد النرجس", "Al Narges Extension")}</td><td class="px-table-cell-x py-table-cell-y">${t("منطقة", "Area")}</td><td class="px-table-cell-x py-table-cell-y">${t("القاهرة الجديدة، القاهرة", "New Cairo, Cairo")}</td><td class="px-table-cell-x py-table-cell-y"><span class="rounded-full bg-success-soft px-2.5 py-1 text-xs font-semibold text-success">${t("منطقة شحن واحدة", "1 shipping zone")}</span></td><td class="px-table-cell-x py-table-cell-y text-end"><button @click="locationModal=true" class="text-xs font-semibold text-accent">${t("تعديل", "Edit")}</button></td></tr><tr class="h-table-row hover:bg-subtle"><td class="px-table-cell-x py-table-cell-y font-semibold">${t("غرب سوميد", "West Somid")}</td><td class="px-table-cell-x py-table-cell-y">${t("منطقة", "Area")}</td><td class="px-table-cell-x py-table-cell-y">${t("٦ أكتوبر، الجيزة", "6th of October, Giza")}</td><td class="px-table-cell-x py-table-cell-y"><span class="rounded-full bg-subtle px-2.5 py-1 text-xs font-semibold text-muted">${t("غير مستخدمة", "Unused")}</span></td><td class="px-table-cell-x py-table-cell-y text-end"><button @click="locationModal=true" class="text-xs font-semibold text-accent">${t("تعديل", "Edit")}</button></td></tr></tbody></table></div>
          <div x-show="view==='empty'" x-cloak class="px-6 py-16 text-center"><h2 class="font-bold">${t("لا توجد مواقع مخصصة", "No custom locations")}</h2><p class="mt-1 text-sm text-muted">${t("استخدم المواقع الأساسية، أو أضف موقعًا خاصًا عند الحاجة.", "Use standard locations, or add a private one when needed.")}</p></div>
        </section>
        <p class="mt-4 rounded-lg border border-info/25 bg-info-soft p-4 text-xs leading-arabic text-info">${t("حذف موقع مستخدم داخل منطقة شحن متوقف لحد ما تشيله من المنطقة أو تستبدله.", "A location used by a shipping zone cannot be deleted until it is removed or replaced.")}</p>
      </div></main>
      <!-- /component: custom-locations -->
      <!-- component: custom-location-modal -->
      <div x-show="locationModal" x-cloak role="dialog" aria-modal="true" class="fixed inset-0 z-overlay grid place-items-center p-4"><button @click="locationModal=false" class="absolute inset-0 bg-ink/45" aria-label="Close"></button><section class="relative w-full max-w-lg rounded-xl border border-border bg-card p-5 shadow-sm"><div class="flex items-center justify-between"><h2 class="font-bold">${t("إضافة موقع مخصص", "Add custom location")}</h2><button @click="locationModal=false" class="grid size-9 place-items-center rounded-md border border-border">×</button></div><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="block"><span class="mb-1.5 block text-sm font-semibold">${t("النوع", "Type")}</span><select class="h-input w-full rounded-md border border-border-strong bg-card px-3 text-sm"><option>Area / منطقة</option><option>City / مدينة</option></select></label><label class="block"><span class="mb-1.5 block text-sm font-semibold">${t("يتبع", "Parent")}</span><select class="h-input w-full rounded-md border border-border-strong bg-card px-3 text-sm"><option>New Cairo / القاهرة الجديدة</option></select></label><label class="block sm:col-span-2"><span class="mb-1.5 block text-sm font-semibold">${t("الاسم بالعربية", "Arabic name")}</span><input value="امتداد النرجس" class="h-input w-full rounded-md border border-border-strong px-3 text-sm" /></label><label class="block sm:col-span-2"><span class="mb-1.5 block text-sm font-semibold">${t("الاسم بالإنجليزية", "English name")}</span><input dir="ltr" value="Al Narges Extension" class="h-input w-full rounded-md border border-border-strong px-3 text-start text-sm" /></label></div><div class="mt-5 flex justify-end gap-2"><button @click="locationModal=false" class="h-control-md rounded-md border border-border-strong px-4 text-sm font-semibold">${t("إلغاء", "Cancel")}</button><button @click="locationModal=false" class="h-control-md rounded-md bg-accent px-4 text-sm font-semibold text-white">${t("حفظ", "Save")}</button></div></section></div>
      <!-- /component: custom-location-modal -->`,
});

const integrations = shell({
  title: "Shipping integrations",
  description: "lala shipping provider integrations overview with Bosta connection states",
  active: "integrations",
  state: "integrationState: 'connected'",
  content: `<!-- component: shipping-integrations -->
      <main class="p-page-mobile sm:p-page-tablet lg:p-page-desktop"><div class="mx-auto max-w-app">
        <div><p class="text-xs font-semibold uppercase tracking-section text-accent">Batch 7 · Shipping</p><h1 class="mt-1 text-2xl font-bold">${t("تكاملات الشحن", "Shipping integrations")}</h1><p class="mt-1 text-sm text-muted">${t("اربط مقدم الشحن المعتمد، وبعدها ابعت الطلبات يدويًا بشكل فردي أو جماعي.", "Connect the approved provider, then submit orders manually one by one or in bulk.")}</p></div>
        <div class="mt-5 flex flex-wrap gap-2 rounded-lg bg-subtle p-2 text-xs"><span class="self-center text-muted">${t("معاينة الحالة:", "Preview state:")}</span><button @click="integrationState='connected'" :class="integrationState==='connected' ? 'bg-ink text-white' : 'bg-card text-muted'" class="rounded-md px-3 py-2">Connected</button><button @click="integrationState='disconnected'" :class="integrationState==='disconnected' ? 'bg-ink text-white' : 'bg-card text-muted'" class="rounded-md px-3 py-2">Not connected</button><button @click="integrationState='error'" :class="integrationState==='error' ? 'bg-ink text-white' : 'bg-card text-muted'" class="rounded-md px-3 py-2">Error</button></div>
        <!-- component: bosta-integration-card -->
        <section class="mt-5 rounded-xl border border-border bg-card p-5 shadow-xs"><div class="flex flex-col gap-5 lg:flex-row lg:items-center"><span class="grid size-14 shrink-0 place-items-center rounded-xl bg-danger-soft font-bold text-danger">B</span><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h2 class="text-lg font-bold">Bosta</h2><span x-show="integrationState==='connected'" class="rounded-full bg-success-soft px-2.5 py-1 text-xs font-semibold text-success">${t("متصل", "Connected")}</span><span x-show="integrationState==='disconnected'" x-cloak class="rounded-full bg-subtle px-2.5 py-1 text-xs font-semibold text-muted">${t("غير متصل", "Not connected")}</span><span x-show="integrationState==='error'" x-cloak class="rounded-full bg-danger-soft px-2.5 py-1 text-xs font-semibold text-danger">${t("يحتاج تدخل", "Needs attention")}</span></div><p class="mt-1 text-sm text-muted">${t("إنشاء الشحنات، حفظ رقم الشحنة والملصق ورابط التتبع، واستقبال تحديثات المزود.", "Create shipments, store tracking number, label and URL, and receive provider events.")}</p><p x-show="integrationState==='connected'" class="mt-2 font-mono text-xs text-muted">Connected 18 Aug 2026 · Last check 2 min ago</p><p x-show="integrationState==='error'" x-cloak class="mt-2 text-xs font-semibold text-danger">${t("فشل آخر تحقق: بيانات الدخول لم تعد صالحة.", "Last validation failed: credentials are no longer valid.")}</p></div><a href="/bosta-connection.html" class="inline-flex h-control-md shrink-0 items-center justify-center rounded-md border border-border-strong px-4 text-sm font-semibold">${t("إدارة الربط", "Manage connection")}</a></div></section>
        <!-- /component: bosta-integration-card -->
        <section class="mt-5 rounded-xl border border-dashed border-border-strong bg-subtle p-6 text-center"><h2 class="font-bold">${t("لا يوجد مقدم شحن آخر معتمد حاليًا", "No other approved shipping provider yet")}</h2><p class="mt-1 text-sm text-muted">${t("أي تكامل جديد يضاف بعد تحديد قواعده وربط أحداثه بحالات الطلب الأساسية.", "A new integration appears only after its rules and core-status event mapping are specified.")}</p></section>
        <section class="mt-5 rounded-xl border border-info/25 bg-info-soft p-5"><h2 class="font-bold text-info">${t("حدود واضحة", "Clear boundaries")}</h2><ul class="mt-3 space-y-2 text-xs leading-arabic text-info"><li>${t("• إنشاء الشحنة لا يغيّر حالة الطلب تلقائيًا.", "• Creating a shipment does not automatically change the order status.")}</li><li>${t("• عند عدم ربط مقدم شحن لا نعرض حقول شركة أو رقم تتبع يدوية.", "• Without a connected provider, manual carrier or tracking fields are not shown.")}</li><li>${t("• وجود شحنة نشطة يمنع إنشاء شحنة مكررة لنفس الطلب.", "• An active shipment blocks duplicate creation for the same order.")}</li></ul></section>
      </div></main>
      <!-- /component: shipping-integrations -->`,
});

const bosta = shell({
  title: "Bosta connection",
  description: "lala Bosta credentials, validation, connected and error states, and exact provider mapping",
  active: "integrations",
  state: "connection: 'connected', revealToken: false",
  content: `<!-- component: bosta-connection -->
      <main class="p-page-mobile sm:p-page-tablet lg:p-page-desktop"><div class="mx-auto max-w-app">
        <div class="flex flex-col gap-4 border-b border-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><a href="/shipping-integrations.html" class="text-xs font-semibold text-accent">${t("← التكاملات", "← Integrations")}</a><h1 class="mt-2 text-2xl font-bold">${t("ربط Bosta", "Connect Bosta")}</h1><p class="mt-1 text-sm text-muted">${t("تحقق من بيانات الربط قبل تفعيل إرسال الطلبات.", "Validate credentials before enabling order submission.")}</p></div><span :class="connection==='connected' ? 'bg-success-soft text-success' : connection==='invalid' ? 'bg-danger-soft text-danger' : 'bg-subtle text-muted'" class="rounded-full px-3 py-1.5 text-xs font-semibold" x-text="connection==='connected' ? (locale==='ar' ? 'متصل' : 'Connected') : connection==='invalid' ? (locale==='ar' ? 'فشل التحقق' : 'Validation failed') : (locale==='ar' ? 'غير متصل' : 'Not connected')"></span></div>
        <div class="mt-6 grid gap-6 xl:grid-cols-editor"><div class="space-y-6">
          <section class="rounded-xl border border-border bg-card p-5 shadow-xs"><div class="flex items-center justify-between"><h2 class="font-bold">${t("بيانات الربط", "Connection credentials")}</h2><span class="text-xs text-muted">${t("لا تظهر بعد الحفظ", "Hidden after save")}</span></div><div class="mt-5 grid gap-5"><label class="block"><span class="mb-1.5 block text-sm font-semibold">${t("مفتاح API", "API key")}</span><div class="flex h-input overflow-hidden rounded-md border border-border-strong"><input :type="revealToken ? 'text' : 'password'" value="demo_key_not_a_secret" autocomplete="off" class="min-w-0 flex-1 px-3 text-start font-mono text-xs outline-none" /><button @click="revealToken=!revealToken" class="border-s border-border px-3 text-xs font-semibold">${t("إظهار", "Show")}</button></div><span class="mt-1.5 block text-xs text-muted">${t("استخدم بيانات Sandbox للمراجعة ثم بيانات Production عند التشغيل الحقيقي.", "Use sandbox credentials for review and production credentials only at real launch.")}</span></label><label class="block"><span class="mb-1.5 block text-sm font-semibold">${t("بيئة الربط", "Environment")}</span><select class="h-input w-full rounded-md border border-border-strong bg-card px-3 text-sm"><option>Sandbox</option><option>Production</option></select></label><div class="flex flex-wrap gap-2"><button @click="connection='connected'" class="h-control-md rounded-md bg-accent px-4 text-sm font-semibold text-white">${t("تحقق واحفظ", "Validate and save")}</button><button @click="connection='invalid'" class="h-control-md rounded-md border border-border-strong px-4 text-sm font-semibold">${t("معاينة خطأ", "Preview error")}</button><button @click="connection='disconnected'" class="h-control-md rounded-md border border-danger/30 px-4 text-sm font-semibold text-danger">${t("فصل الربط", "Disconnect")}</button></div></div></section>
          <section x-show="connection==='connected'" class="rounded-xl border border-success/25 bg-success-soft p-5 text-success"><h2 class="font-bold">${t("تم التحقق من الاتصال", "Connection validated")}</h2><p class="mt-1 text-xs">${t("يمكن الآن إرسال الطلبات إلى Bosta بشكل فردي أو جماعي.", "Orders can now be submitted to Bosta individually or in bulk.")}</p><p dir="ltr" class="mt-3 font-mono text-xs">Validated 22 Aug 2026 · 18:42 Cairo</p></section><section x-show="connection==='invalid'" x-cloak class="rounded-xl border border-danger/25 bg-danger-soft p-5 text-danger"><h2 class="font-bold">${t("فشل التحقق من بيانات الدخول", "Credential validation failed")}</h2><p class="mt-1 text-xs leading-arabic">${t("Bosta رفضت المفتاح. راجع البيئة والمفتاح ثم أعد المحاولة؛ إرسال الطلبات يظل متوقفًا.", "Bosta rejected the key. Check the environment and key, then retry; order submission remains disabled.")}</p></section><section x-show="connection==='disconnected'" x-cloak class="rounded-xl border border-border bg-subtle p-5 text-muted"><h2 class="font-bold">${t("Bosta غير متصلة", "Bosta is not connected")}</h2><p class="mt-1 text-xs">${t("لن تظهر إجراءات الإرسال داخل الطلبات حتى يتم ربط الحساب.", "Submission actions remain hidden from orders until the account is connected.")}</p></section>
        </div><aside class="self-start space-y-5 xl:sticky xl:top-24">
          <!-- component: bosta-status-mapping -->
          <section class="rounded-xl border border-border bg-card p-5 shadow-xs"><h2 class="font-bold">${t("ربط أحداث Bosta", "Bosta event mapping")}</h2><p class="mt-1 text-xs text-muted">${t("المجموعة الأساسية ثابتة ولا يمكن إضافة حالة جديدة.", "The core set is fixed; no new status can be added.")}</p><dl class="mt-4 space-y-3 text-xs"><div class="flex items-center justify-between gap-3"><dt class="font-mono">accepted</dt><dd class="rounded-full bg-warning-soft px-2.5 py-1 font-semibold text-warning">${t("قيد المعالجة", "Processing")}</dd></div><div class="flex items-center justify-between gap-3"><dt class="font-mono">picked up / in transit</dt><dd class="rounded-full bg-info-soft px-2.5 py-1 font-semibold text-info">${t("تم الشحن", "Shipped")}</dd></div><div class="flex items-center justify-between gap-3"><dt class="font-mono">delivered</dt><dd class="rounded-full bg-success-soft px-2.5 py-1 font-semibold text-success">${t("تم التسليم", "Delivered")}</dd></div><div class="flex items-center justify-between gap-3"><dt class="font-mono">cancelled</dt><dd class="rounded-full bg-danger-soft px-2.5 py-1 font-semibold text-danger">${t("ملغي", "Cancelled")}</dd></div><div class="flex items-center justify-between gap-3"><dt class="font-mono">returned</dt><dd class="rounded-full bg-subtle px-2.5 py-1 font-semibold text-muted">${t("مرتجع", "Returned")}</dd></div></dl></section>
          <!-- /component: bosta-status-mapping -->
          <section class="rounded-xl border border-info/25 bg-info-soft p-4 text-xs leading-arabic text-info">${t("التحديثات القادمة من Bosta تطبق الربط الموضح، لكن مجرد إنشاء الشحنة لا يغيّر حالة الطلب.", "Incoming Bosta events use this mapping, but shipment creation alone does not change the order status.")}</section>
        </aside></div>
      </div></main>
      <!-- /component: bosta-connection -->`,
});

for (const [name, source] of Object.entries({
  "shipping-zones.html": zones,
  "shipping-zone-editor.html": zoneEditor,
  "custom-locations.html": locations,
  "shipping-integrations.html": integrations,
  "bosta-connection.html": bosta,
})) await writeFile(resolve(publicRoot, name), source, "utf8");

console.log("Generated five Batch 7 shipping and Bosta screens.");
